apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "import-demo-app4"
  annotations:
    github.com/project-slug: himanshu-dev-hub-training-organization/import-demo4 # <organization_name>/<project_name>
spec:
  type: service
  lifecycle: development
  owner: "group:default/unset-owner"
